### ISSUE TITLE
[Function] Moon phase reminder

### ISSUE THREAD

**Issue by SeanChengN** [Ellpeck/Nyx#1]
The moon phase is difficult to identify for me, if it can pop up a reminder when night is coming will be better.
E.g
![2019-10-26_10 41 41](https://user-images.githubusercontent.com/20624068/67613271-21993580-f7de-11e9-912f-cfdf1bf05cb0.jpg)
by Photoshop

**Comment by majijn** [comment]
thats too much 

a small message like the one you get when its daylight and you try to sleep is more reasonable

**Comment by Ellpeck** [comment]
I'm sorry, but this mod was a commission and, as such, I won't be adding any features from suggestions.
