### ISSUE TITLE
Drinking stacked lunar water consumes entire stack

### ISSUE THREAD

**Issue by tyon2006** [Ellpeck/Nyx#14]
So, this isn't a direct issue with Nyx, but I'm using Nyx for a modpack and I'm hoping you'll help me out. When i use other mods to increase the stack size of the Lunar Water bottles (from 1 to 16), it works, but if you drink 1, it eats the whole stack and spits out only one empty bottle. 

I've tried the same stacking method with potions, and the stack consumes 1  and drops an empty bottle as expected. Lunar water is the only drinkable item I've seen do this, so I think its something to do with the drinking action. Can you please help?

**Comment by Ellpeck** [comment]
I assume that's whatever mod you're using to increase the stack size changing vanilla potion code, since I just copy-pasted the regular potion drinking code.

**Comment by tyon2006** [comment]
I tried this with quark and stackie. Quark might change the code, stackie does not and I only see this behavior with the lunar water bottle. 

So, any chance I could put in a feature request to allow increasing the stack size of the lunar water?

**Comment by tyon2006** [comment]
Another thought occurs to me - Instead of copying and pasting the code for the potion, could you extend the potion class instead? It could very well inherit any supposed modification to the potion code of other mods if you did.

**Comment by Ellpeck** [comment]
no because the potion code has a million other things in it that the lunar water bottle doesn't need

**Comment by CalaMariGold** [comment]
Rebirth of the Night increases all potion stack sizes, so lunar water should behave the same.

**Comment by tyon2006** [comment]
If I can recommend, go to the code here: https://github.com/Ellpeck/Nyx/blob/master/src/main/java/de/ellpeck/nyx/items/LunarWaterBottle.java#L52

And implement something that checks the itemstack size:
https://www.programcreek.com/java-api-examples/?class=net.minecraftforge.event.ForgeEventFactory&method=onItemUseFinish

Sorry for the links, but I'm thinking that's what would fix this.
