### ISSUE TITLE
[Enhancement/compatibility] Book enchancement descriptions

### ISSUE THREAD

**Issue by pimalel233** [Ellpeck/Nyx#19]
Hi, could you add an option to disable your enchantement descriptions so when used with a mod EnchantmentDescriptions it could use its description way of showing? Currently with Nyx installed, the description is doubled. I solved in in earlier version by commenting out the code somewhere in your mod which adds your description and compiling the mod for myself, but I think it could be a nice feature to manually disable it in config if needed. A screenshot with Nyx+EnchantmentDescriptions:
http://prntscr.com/rxdhxh
EnchantmentDescriptions+working book (as it should look like):
http://prntscr.com/rxdjb2
My old recompiled Nyx 1.1.0 +EnchantmentDescriptions:
http://prntscr.com/rxdjrd
Great mod, glad it's getting more updates :)

**Comment by Ellpeck** [comment]
Sorry, this mod was a commission, and as such, I do not accept any feature requests.
