### ISSUE TITLE
inspirations support

### ISSUE THREAD

**Issue by majijn** [Ellpeck/Nyx#2]
inspirations has modules which change the functionality of the cauldron to be able to hold any fluid

it also has the option to drop the fluid if you mine the cauldron in the world, this option being enabled causes lunar water to be unobtainable as in its place you end up with a water source block instead of a nyx crucible with lunar water

**Comment by nephatrine** [comment]
Yes, would very much like to be able to get lunar water in my Inspirations cauldron.

**Comment by katubug** [comment]
I am also considering adding both these mods, I'd like this as well!

**Comment by Ellpeck** [comment]
I'm sorry, but this mod was a commission and, as such, I won't be adding any features from suggestions.

**Comment by majijn** [comment]
if the issue is closed  the commissioner might not see it :(

**Comment by Kompreya** [comment]
> I'm sorry, but this mod was a commission and, as such, I won't be adding any features from suggestions.

We commissioned it. As such, would you be willing to let others do PRs with such changes and feature requests?

**Comment by Ellpeck** [comment]
Yes.
