### ISSUE TITLE
Missing texture

### ISSUE THREAD

**Issue by hasuu** [Ellpeck/Nyx#22]
The minecraft flower pot has no texture.

**Comment by Ellpeck** [comment]
ok? what does that have to do with Nyx

**Comment by hasuu** [comment]
> ok? what does that have to do with Nyx

when i have nyx installed with couple of other mods the minecraft pot has no texture

**Comment by Ellpeck** [comment]
Please figure out which mod is actually causing this issue.

**Comment by hasuu** [comment]
ok gonna do it now
