### ISSUE TITLE
Question regarding Mob Controller & PeacefulSurface  

### ISSUE THREAD

**Issue by Keetarin** [Ellpeck/Nyx#31]
I know that the Bloodmoon mod is an optional dependency for those two mods and that during a bloodmoon from Bloodmoon that the limits from them can be disabled. Does your mod also proc that function? 
If not, could you see if you can trigger it?

**Comment by Ellpeck** [comment]
Sorry, this mod was a commission, and as such, I do not accept any feature requests.

**Comment by Keetarin** [comment]
I didn't know it was a commission. 
Sorry if it sounded like I was making a request, I just wanted to know if they were compatible and was asking if you could check since my computer is out of commission for the foreseeable future (Need to take it in for maintenence).
