### ISSUE TITLE
[1.12.2] Moon colors for Harvest/Blood Moon don't show if Astral Sorcery is installed.

### ISSUE THREAD

**Issue by Z-Tunic** [Ellpeck/Nyx#37]
Minecraft: 1.12.2
Forge: 14.23.5.2854

Mods: 3
astralsorcery-1.12.2-1.10.27
Baubles-1.12-1.5.2
Nyx-1.3.0

=====

I... am not sure if it's possible to add compact with Astral Sorcery to allow the moon to change it's color during a harvest / blood moon. At the moment the moon appears to change color but then it returns back to it's default color once it rises. Here's some screenshots.

![](https://cdn.discordapp.com/attachments/377171551155650560/766046787169419284/nyxmoonastral.PNG)

Left is without astral sorcery OR the dimension is added to the 'weakSkyRenders' in AS config.
Right is with astral sorcery OR the dimension isn't added to the 'weakSkyRenders' in AS config.

**Comment by Ellpeck** [comment]
I assume Astral changes the way the sky/moon is rendered, so there's not much I can do about this.
Nyx's way of changing the moon color is rather hacky as well, so I doubt they'll be able to be made compatible easily.
