### ISSUE TITLE
nyx:worm

### ISSUE THREAD

**Issue by majijn** [Ellpeck/Nyx#4]
![2019-11-05_01 18 40](https://user-images.githubusercontent.com/18368034/68169084-32c70c80-ff6b-11e9-86bd-8e7d7d59a593.png)
![2019-11-05_01 19 32](https://user-images.githubusercontent.com/18368034/68169086-335fa300-ff6b-11e9-9972-182e30fb2b32.png)

**Comment by Ellpeck** [comment]
Note to self: Change registry names of copied code lol
