### ISSUE TITLE
Cauldrons not producing nyx water event on sponge server

### ISSUE THREAD

**Issue by tyon2006** [Ellpeck/Nyx#46]
I'm using Nyx in my modpack. I found that if I use it in local client the overnight nyx water bubbles event occurs just fine. If I go online, the bubbles never occur. The only difference between the two environments is that I am using spongeforge. Any ideas on what could be causing this?

I'm not aware of anything Sponge does to the cauldron - This could just be a red herring. Any ideas you might have would be appreciated.

**Comment by Ellpeck** [comment]
Please try to reproduce this issue on a regular Forge server.

**Comment by tyon2006** [comment]
![image](https://user-images.githubusercontent.com/26413035/129752904-7ad723d5-81ae-42b1-a15f-cc84bfeef982.png)

Just removed SpongeForge and tried again. Confirmed that the particle effect event works and the cauldron responds to lapis and makes nyx water as expected.

Any ideas on how I could troubleshoot this further?

**Comment by Ellpeck** [comment]
Sadly not. This looks to be an issue with Sponge, so you should try to report it to them.
