### ISSUE TITLE
Unable to disable further meteors, without completely removing meteor content

### ISSUE THREAD

**Issue by iLLHunter** [Ellpeck/Nyx#54]
Way too many meteors are falling, 3-4 new ones every time i go out for a walk. really starting to make the overworld look crappy. I don't want to remove all the meteor content, I'd just like to stop more from falling. 

I have all the chances set to 0.0 relaunched game but meteors continue to fall 

![image](https://github.com/user-attachments/assets/bfadc2dc-4135-453c-a9c4-09b174b94ebd)

**Comment by iLLHunter** [comment]
an option to control the dimensions in which they spawn at would be ideal, but that may not be possible at this point

**Comment by Ellpeck** [comment]
Hi! Unfortunately, this mod is not officially supported anymore. Sorry :(

**Comment by iLLHunter** [comment]
Not supported.... so there is no way to disable meteors, the config is broken? 
I'm not expecting updates, just an answer, but if the mod ignores its own config, that is my answer.

**Comment by Ellpeck** [comment]
Setting the chance to 0 makes it extremely unlikely, but still possible, for an event to happen: https://github.com/Ellpeck/Nyx/blob/995d3b45b54391d1a5b599b42c5b2d2e99e6ef19/src/main/java/de/ellpeck/nyx/lunarevents/LunarEvent.java#L88

You can potentially set the chance to a negative number to make it unable to happen entirely.

Hmm, actually this isn't the case with meteors, where a chance of 0 is explicitly checked: https://github.com/Ellpeck/Nyx/blob/995d3b45b54391d1a5b599b42c5b2d2e99e6ef19/src/main/java/de/ellpeck/nyx/events/Events.java#L233

I'm not sure why this happens then :(

**Comment by iLLHunter** [comment]
Ok. I appreciate your help, and again, thanks for making the mod. 

I will take care of it
