### ISSUE TITLE
Feature: Wolves get buffs on blue moon

### ISSUE THREAD

**Issue by denzuko** [Ellpeck/Nyx#6]
Scenario: Tame wolves are energetic
   Given one has a tamed wolf
   And there is a Blue moon in the sky
   Then Tamed wolf gets speed 1 buff

Scenario: Wild wolves are stronger, meaner, and more frequent
  Given a blue is in the sky
  Then for a configurable percent wolves should spawn in packs of 3-5 within wooded biomes
  And Wild wolves should get strength buff
  And Wild wolves should be hostile

**Comment by Ellpeck** [comment]
I'm sorry, but this mod was a commission and, as such, I won't be adding any features from suggestions.

**Comment by denzuko** [comment]
mind if I write an add-on that implements these features then?
