### ISSUE TITLE
Feature: Ambient sounds - Howls

### ISSUE THREAD

**Issue by denzuko** [Ellpeck/Nyx#7]
Scenario:
  Given one is in wooded, cold, or highland biomes
  And there is a full or blue moon
  Then one should hear a periodic howls around high moon

**Comment by Ellpeck** [comment]
I'm sorry, but this mod was a commission and, as such, I won't be adding any features from suggestions.

**Comment by MagmaSlime123** [comment]
People will keep suggesting things. So better off adding these types of things.

**Comment by Ellpeck** [comment]
Oh you are so right. I'm sorry, my master
