### ISSUE TITLE
Question regarding Blood Moon mod compat

### ISSUE THREAD

**Issue by katubug** [Ellpeck/Nyx#8]
Hi! I normally would just ask a question like this at the mod page, but since comments are disabled, here I am, hopefully that's okay!

I want to use this mod and Bloodmoon together - is there a way to make them compatible? Deactivating the similar feature from Nyx or something? Any help is welcome!

**Comment by katubug** [comment]
Oh! And one additional question: does the enchanting-at-night restriction work with mods that alter the enchanting system, such as Enchanting Plus?

**Comment by Ellpeck** [comment]
There's not a feature in Nyx that's similar to the Blood Moon. Also, the enchanting-at-night restriction most likely won't work with other mods, as the only thing it disables is the ability to right-click a vanilla enchanting table.
